# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11EIynBbnisXqX3T5KRoE4_fRIxb37dqH
"""

!pip install pandas numpy matplotlib seaborn scikit-learn
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns
from sklearn.cluster import KMeans
from sklearn.ensemble import RandomForestRegressor
from sklearn.preprocessing import StandardScaler
import re

# Set plot style
plt.style.use("seaborn-v0_8-whitegrid")
plt.rcParams["font.family"] = "sans-serif"

# 1. Load Data
df = pd.read_csv("youtube_4k_channels_cleaned.csv")

# Robustly standardize column names: strip whitespace, lowercase, replace non-alphanumeric (except underscores) with underscores
def clean_col_name(col_name):
    col_name = col_name.strip().lower()
    col_name = re.sub(r'[^a-z0-9_]+', '_', col_name) # Replace non-alphanumeric with underscore
    col_name = re.sub(r'_+', '_', col_name) # Replace multiple underscores with single
    return col_name.strip('_') # Remove leading/trailing underscores

df.columns = [clean_col_name(col) for col in df.columns]

print("DataFrame columns after cleaning:", df.columns.tolist())

# 2. Clean & Preprocess
df.drop_duplicates(inplace=True)
# Removed 'category' from subset as it is not present in the dataframe.
# Changed 'video_views' to 'total_views' and 'video_count' to 'total_videos'.
df.dropna(
    subset=["subscribers", "total_views", "total_videos"], inplace=True
)

numeric_cols = ["subscribers", "total_views", "total_videos"]
for col in numeric_cols:
    df[col] = pd.to_numeric(df[col], errors="coerce")

df.dropna(subset=numeric_cols, inplace=True)
df = df[
    (df["subscribers"] > 0) & (df["total_views"] > 0) & (df["total_videos"] > 0)
].copy()

# Feature Engineering
df["views_per_video"] = np.round(df["total_views"] / df["total_videos"], 2)
df["subs_per_video"] = np.round(df["subscribers"] / df["total_videos"], 2)
df["engagement_proxy"] = np.round((df["total_views"] / df["subscribers"]), 2)

# Category Aggregation
# This section will likely cause a KeyError because 'category' column is missing.
# You may need to provide an alternative column for categorization or adjust the analysis.
cat_df = (
    df.groupby("channel_name") # Temporarily using 'channel_name' to avoid immediate KeyError, but this needs clarification.
    .agg(
        total_channels=("subscribers", "count"),
        total_subs=("subscribers", "sum"),
        total_views=("total_views", "sum"),
        avg_subs=("subscribers", "mean"),
        avg_views=("total_views", "mean"),
        avg_vpv=("views_per_video", "mean"),
        avg_engagement=("engagement_proxy", "mean"),
    )
    .reset_index()
)

# 3. ML Models (Growth & Trending Prediction)
X = cat_df[["total_channels", "total_views", "avg_vpv", "avg_engagement"]]
y = cat_df["avg_subs"]

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

model = RandomForestRegressor(n_estimators=100, random_state=42)
model.fit(X_scaled, y)

cat_df["predicted_growth_score"] = model.predict(X_scaled)
cat_df["growth_rank"] = cat_df["predicted_growth_score"].rank(
    ascending=False, method="min"
)

cluster_features = cat_df[
    ["avg_views", "avg_vpv", "avg_engagement", "total_channels"]
]
cluster_scaled = scaler.fit_transform(cluster_features)

kmeans = KMeans(n_clusters=3, random_state=42, n_init=10)
cat_df["trend_cluster"] = kmeans.fit_predict(cluster_scaled)

cat_df["trending_index"] = np.round(
    (
        StandardScaler().fit_transform(cat_df[["avg_vpv"]]).flatten() * 0.4
        + StandardScaler()
        .fit_transform(cat_df[["avg_engagement"]])
        .flatten()
        * 0.4
        + StandardScaler().fit_transform(cat_df[["avg_views"]]).flatten() * 0.2
    ),
    2,
)

cat_df["trending_rank"] = cat_df["trending_index"].rank(
    ascending=False, method="min"
)

# 4. Pipeline Flowchart Visual Representation
fig, ax = plt.subplots(figsize=(10, 2))
ax.axis("off")

boxes = [
    "Raw CSV Data",
    "Data Cleaning &\nFeature Eng.",
    "Category Aggregation\n& Scaling",
    "ML Models\n(RF & K-Means)",
    "Growth & Trend\nPredictions",
]

for i, box in enumerate(boxes):
    ax.text(
        i * 2.2,
        0.5,
        box,
        ha="center",
        va="center",
        color="white",
        weight="bold",
        bbox=dict(
            boxstyle="round,pad=0.6",
            facecolor="#1f77b4" if i < 3 else "#ff7f0e",
            edgecolor="none",
        ),
    )
    if i < len(boxes) - 1:
        ax.annotate(
            "",
            xy=(i * 2.2 + 1.1, 0.5),
            xytext=(i * 2.2 + 0.9, 0.5),
            arrowprops=dict(arrowstyle="->", lw=2, color="gray"),
        )

ax.set_xlim(-1, len(boxes) * 2.2 - 1)
ax.set_ylim(0, 1)
plt.title(
    "YouTube Prediction Analytics Pipeline Flowchart",
    fontsize=14,
    weight="bold",
)
plt.tight_layout()
plt.show()

# 5. Visual Dashboard Graphs
fig, axes = plt.subplots(2, 2, figsize=(16, 12))

# Graph 1: Top Growth Categories
top_growth = cat_df.sort_values(by="growth_rank").head(7)
sns.barplot(
    data=top_growth,
    x="predicted_growth_score",
    y="channel_name", # Changed to 'channel_name' as 'category' is missing
    palette="Blues_r",
    ax=axes[0, 0],
)
axes[0, 0].set_title(
    "Predicted Growth Potential by Channel Name", fontsize=12, weight="bold"
)
axes[0, 0].set_xlabel("Predicted Growth Score")
axes[0, 0].set_ylabel("Channel Name")

# Graph 2: Top Trending Categories
top_trending = cat_df.sort_values(by="trending_rank").head(7)
sns.barplot(
    data=top_trending,
    x="trending_index",
    y="channel_name", # Changed to 'channel_name' as 'category' is missing
    palette="Oranges_r",
    ax=axes[0, 1],
)
axes[0, 1].set_title("Trending Index by Channel Name", fontsize=12, weight="bold")
axes[0, 1].set_xlabel("Trending Index")
axes[0, 1].set_ylabel("Channel Name")

# Graph 3: Engagement vs Views per Video Cluster Analysis
sns.scatterplot(
    data=cat_df,
    x="avg_vpv",
    y="avg_engagement",
    hue="trend_cluster",
    size="total_channels",
    sizes=(50, 400),
    palette="viridis",
    ax=axes[1, 0],
)
axes[1, 0].set_title(
    "Channel Clustering (K-Means)", fontsize=12, weight="bold"
)
axes[1, 0].set_xlabel("Average Views Per Video")
axes[1, 0].set_ylabel("Average Engagement Proxy")

# Graph 4: Feature Correlations
corr = df[["subscribers", "total_views", "total_videos", "views_per_video"]].corr()
sns.heatmap(
    corr, annot=True, cmap="coolwarm", fmt=".2f", ax=axes[1, 1], cbar=False
)
axes[1, 1].set_title(
    "Feature Correlation Matrix", fontsize=12, weight="bold"
)

plt.tight_layout()
plt.show()

# Terminal Outputs
print("--- CHANNEL GROWTH PREDICTION RESULT ---")
print(
    cat_df.sort_values(by="growth_rank")[
        [
            "channel_name", # Changed to 'channel_name'
            "total_channels",
            "avg_subs",
            "predicted_growth_score",
            "growth_rank",
        ]
    ]
    .head(5)
    .to_string(index=False)
)

print("\n--- TRENDING CHANNEL PREDICTION RESULT ---")
print(
    cat_df.sort_values(by="trending_rank")[
        [
            "channel_name", # Changed to 'channel_name'
            "avg_views",
            "avg_vpv",
            "avg_engagement",
            "trending_index",
            "trending_rank",
        ]
    ]
    .head(5)
    .to_string(index=False)
)